version: '3'
services:
  web:
    build: .
    ports:
      - "8080:3000"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - nodean_net
  db:
    image: "mysql"
    environment:
      - MYSQL_ROOT_PASSWORD=Alpha
      - MYSQL_DATABASE=nodean
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$$MYSQL_ROOT_PASSWORD" ]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
    networks:
      - nodean_net
    volumes:
      - db-data:/foo

networks:
  nodean_net:
volumes:
  db-data: